name: Build and Push

on:
  push:
    branches:
      - main
    paths:
      - "slides.md"
      - "**.bib"
      - "**.csl"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        uses: docker://pandoc/crossref:2.16
        with:
          args: >-
            --standalone
            --self-contained
            --citeproc
            --slide-level=2
            -t revealjs
            --output=docs/index.html
            slides.md

      - name: commit and push
        uses: EndBug/add-and-commit@v7
        with:
          add: "docs"
          push: true
